countries_cities = {
    "USA": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose"],
    "Canada": ["Toronto", "Montreal", "Calgary", "Ottawa", "Edmonton", "Mississauga", "Winnipeg", "Vancouver", "Brampton", "Hamilton"],
    "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig"],
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
    "UK": ["London", "Birmingham", "Leeds", "Glasgow", "Sheffield", "Bradford", "Liverpool", "Edinburgh", "Manchester", "Bristol"],
    "Japan": ["Tokyo", "Osaka", "Kyoto", "Hokkaido", "Fukuoka", "Sapporo", "Nagoya", "Hiroshima", "Sendai", "Kobe"],
    "Brazil": ["São Paulo", "Rio de Janeiro", "Salvador", "Brasília", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen"],
    "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Nizhny Novgorod", "Samara", "Omsk", "Kazan", "Chelyabinsk", "Rostov-on-Don"],
    "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao"],
    "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur"],
    "China": ["Beijing", "Shanghai", "Chongqing", "Tianjin", "Guangzhou", "Shenzhen", "Chengdu", "Nanjing", "Wuhan", "Hangzhou"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
    "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan"],
    "Uruguay": ["Montevideo", "Salto", "Ciudad de la Costa", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes"],
    "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Arica", "Talca", "Chillán"],
    "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "Ciudad Juárez", "León", "Zapopan", "Cancún", "Querétaro"],
    "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Bray", "Navan", "Ennis"],
    "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori"],
    "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg"],
    "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde"],
    "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Goyang", "Seongnam"],
}

phone_country_codes = {
    "USA": "+1",
    "Canada": "+1",
    "Germany": "+49",
    "France": "+33",
    "UK": "+44",
    "Japan": "+81",
    "Brazil": "+55",
    "Sweden": "+46",
    "Netherlands": "+31",
    "Russia": "+7",
    "Spain": "+34",
    "India": "+91",
    "China": "+86",
    "Italy": "+39",
    "Argentina": "+54",
    "Uruguay": "+598",
    "Chile": "+56",
    "Mexico": "+52",
    "Ireland": "+353",
    "Finland": "+358",
    "Norway": "+47",
    "Denmark": "+45",
    "South Korea": "+82"
}

popular_first_name = {
    "USA": ["James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", "William", "Elizabeth"],
    "Canada": ["Liam", "Olivia", "Noah", "Emma", "Oliver", "Ava", "Ethan", "Sophia", "Lucas", "Charlotte"],
    "Germany": ["Maximilian", "Sophia", "Alexander", "Marie", "Paul", "Maria", "Leon", "Sophie", "Felix", "Emilia"],
    "France": ["Lucas", "Emma", "Louis", "Jade", "Gabriel", "Louise", "Arthur", "Alice", "Adam", "Chloé"],
    "UK": ["Oliver", "Olivia", "George", "Amelia", "Harry", "Isla", "Noah", "Ava", "Jack", "Emily"],
    "Japan": ["Haruto", "Yuto", "Sota", "Yuki", "Hayato", "Haruka", "Hina", "Yui", "Rin", "Sakura"],
    "Brazil": ["Miguel", "Arthur", "Davi", "Gabriel", "Pedro", "Alice", "Sophia", "Helena", "Valentina", "Laura"],
    "Sweden": ["Elias", "William", "Lucas", "Oliver", "Liam", "Alice", "Maja", "Ella", "Elsa", "Olivia"],
    "Netherlands": ["Daan", "Noah", "Sem", "Lucas", "Jesse", "Emma", "Tess", "Sophie", "Julia", "Anna"],
    "Russia": ["Alexander", "Mikhail", "Maxim", "Ivan", "Artem", "Sofia", "Anastasia", "Darya", "Maria", "Ksenia"],
    "Spain": ["Lucas", "Mateo", "Martín", "Daniel", "Pablo", "Lucía", "Sofía", "Martina", "Maria", "Paula"],
    "India": ["Aarav", "Vivaan", "Aditya", "Vikram", "Arjun", "Saanvi", "Ananya", "Aadhya", "Pari", "Diya"],
    "China": ["Wei", "Ming", "Fang", "Jie", "Wei", "Ying", "Feng", "Huan", "Liang", "Chen"],
    "Italy": ["Francesco", "Alessandro", "Matteo", "Lorenzo", "Leonardo", "Sofia", "Giulia", "Aurora", "Alice", "Ginevra"],
    "Argentina": ["Benjamín", "Mateo", "Santiago", "Thiago", "Martín", "Sofía", "Emma", "Valentina", "Lucía", "Martina"],
    "Uruguay": ["Santiago", "Mateo", "Martín", "Rodrigo", "Lucas", "Sofía", "Valentina", "Martina", "Lucía", "Emilia"],
    "Chile": ["Agustín", "Mateo", "Santiago", "Benjamín", "Vicente", "Sofía", "Emilia", "Isabella", "Emma", "Valentina"],
    "Mexico": ["José", "Luis", "Juan", "Miguel", "Carlos", "María", "Juana", "Elena", "Patricia", "Carmen"],
    "Ireland": ["Jack", "James", "Noah", "Conor", "Daniel", "Emily", "Grace", "Sophie", "Lily", "Amelia"],
    "Finland": ["Juhani", "Olavi", "Antero", "Tapani", "Mikael", "Maria", "Sofia", "Anneli", "Johanna", "Kaarina"],
    "Norway": ["Jakob", "Lucas", "Filip", "Oskar", "Noah", "Emma", "Nora", "Olivia", "Sofia", "Mia"],
    "Denmark": ["William", "Noah", "Oscar", "Lucas", "Victor", "Emma", "Ida", "Clara", "Anna", "Sofia"],
    "South Korea": ["Min-jun", "Seo-yeon", "Si-woo", "Ji-ho", "Ha-eun", "Ji-woo", "Jung-hwan", "So-yi", "Hyun-woo", "Jung-woo"]
}

popular_last_name = {
    "USA": ["Smith", "Johnson", "Williams", "Brown", "Jones"],
    "Canada": ["Smith", "Brown", "Tremblay", "Martin", "Roy"],
    "Germany": ["Müller", "Schmidt", "Schneider", "Fischer", "Weber"],
    "France": ["Martin", "Bernard", "Dubois", "Thomas", "Robert"],
    "UK": ["Smith", "Jones", "Taylor", "Brown", "Wilson"],
    "Japan": ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe"],
    "Brazil": ["Silva", "Santos", "Oliveira", "Souza", "Rodrigues"],
    "Sweden": ["Johansson", "Andersson", "Karlsson", "Nilsson", "Larsson"],
    "Netherlands": ["De Jong", "Jansen", "De Vries", "Van den Berg", "Van Dijk"],
    "Russia": ["Ivanov", "Smirnov", "Kuznetsov", "Popov", "Vasilyev"],
    "Spain": ["García", "Fernández", "González", "Rodríguez", "López"],
    "India": ["Patel", "Singh", "Kumar", "Sharma", "Gupta"],
    "China": ["Wang", "Li", "Zhang", "Liu", "Chen"],
    "Italy": ["Rossi", "Russo", "Ferrari", "Esposito", "Bianchi"],
    "Argentina": ["González", "Rodríguez", "Gómez", "Fernández", "López"],
    "Uruguay": ["Pérez", "González", "Rodríguez", "Fernández", "López"],
    "Chile": ["González", "Muñoz", "Rojas", "Díaz", "Pérez"],
    "Mexico": ["Hernández", "García", "Martínez", "López", "González"],
    "Ireland": ["Murphy", "Kelly", "O'Sullivan", "Walsh", "Smith"],
    "Finland": ["Korhonen", "Virtanen", "Mäkinen", "Nieminen", "Mäkelä"],
    "Norway": ["Hansen", "Johansen", "Olsen", "Larsen", "Andersen"],
    "Denmark": ["Jensen", "Nielsen", "Hansen", "Pedersen", "Andersen"],
    "South Korea": ["Kim", "Lee", "Park", "Choi", "Jung"]
}

email_providers = [
    'gmail.com',
    'yahoo.com',
    'outlook.com',
    'aol.com',
    'hotmail.com',
    'icloud.com',
    'mail.com',
    'yandex.com',
    'protonmail.com',
    'proton.me',
    'zoho.com',
    'gmx.com',
    'fastmail.com',
    'hushmail.com',
    'tutanota.com',
    'live.com',
    'msn.com',
    'me.com'
]


random_address = {
    'Address_1': 'Linden Oak Ash 923 Drive',
    'Address_2': 'Birch Holly Hazel Oak 48 Avenue',
    'Address_3': 'Linden Hazel 945 Street',
    'Address_4': 'Cedar Willow 906 Street',
    'Address_5': 'Beech Ash Cherry 548 Avenue',
    'Address_6': 'Beech Birch Cedar 463 Road',
    'Address_7': 'Hazel Elm Maple Cedar 549 Road',
    'Address_8': 'Holly Ivy Beech 1100 Avenue',
    'Address_9': 'Linden Maple Beech Ash 539 Avenue',
    'Address_10': 'Pine Elm Willow 409 Street',
    'Address_11': 'Holly Cherry Beech 840 Drive',
    'Address_12': 'Ash Ivy 437 Avenue',
    'Address_13': 'Birch Cherry 640 Road',
    'Address_14': 'Holly Ivy 683 Road',
    'Address_15': 'Ash Spruce Maple 32 Street',
    'Address_16': 'Willow Hazel Elm 128 Street',
    'Address_17': 'Cherry Beech Cedar Linden 1179 Road',
    'Address_18': 'Holly Spruce Elm Birch 1110 Avenue',
    'Address_19': 'Ivy Ash Beech Holly 550 Avenue',
    'Address_20': 'Spruce Beech Maple 828 Road',
    'Address_21': 'Birch Cherry Hazel 839 Road',
    'Address_22': 'Beech Maple Ash 96 Avenue',
    'Address_23': 'Spruce Beech Linden 860 Road',
    'Address_24': 'Birch Oak 1126 Drive',
    'Address_25': 'Willow Elm Hazel 549 Drive',
    'Address_26': 'Ash Oak Ivy 47 Drive',
    'Address_27': 'Beech Cherry Maple Holly 823 Street',
    'Address_28': 'Spruce Cedar Linden 464 Avenue',
    'Address_29': 'Holly Ivy Ash 633 Drive',
    'Address_30': 'Elm Birch Linden 15 Street',
    'Address_31': 'Spruce Beech 870 Street',
    'Address_32': 'Elm Spruce Willow Birch 251 Drive',
    'Address_33': 'Maple Cherry 207 Avenue',
    'Address_34': 'Cedar Oak 996 Drive',
    'Address_35': 'Willow Elm 1185 Avenue',
    'Address_36': 'Ash Ivy Willow 423 Avenue',
    'Address_37': 'Beech Oak Holly Birch 446 Street',
    'Address_38': 'Ivy Beech 1185 Avenue',
    'Address_39': 'Willow Ivy Cedar 476 Avenue',
    'Address_40': 'Linden Cherry Maple 499 Street',
    'Address_41': 'Willow Linden 764 Avenue',
    'Address_42': 'Maple Spruce 442 Road',
    'Address_43': 'Pine Willow Elm 448 Road',
    'Address_44': 'Birch Elm Ivy Hazel 1185 Avenue',
    'Address_45': 'Beech Hazel Cedar Birch 950 Avenue',
    'Address_46': 'Elm Ivy 1029 Road',
    'Address_47': 'Holly Spruce 431 Drive',
    'Address_48': 'Cedar Maple 714 Street',
    'Address_49': 'Ivy Oak Cherry 345 Avenue',
    'Address_50': 'Holly Pine Beech 231 Road',
    'Address_51': 'Birch Ivy Maple Spruce 935 Road',
    'Address_52': 'Linden Maple Cherry Elm 216 Road',
    'Address_53': 'Ash Beech Linden 302 Drive',
    'Address_54': 'Elm Birch Ash 259 Road',
    'Address_55': 'Hazel Holly Cedar Ash 164 Avenue',
    'Address_56': 'Linden Maple 389 Street',
    'Address_57': 'Cedar Ivy Birch 78 Street',
    'Address_58': 'Beech Holly 561 Avenue',
    'Address_59': 'Willow Spruce Linden 824 Drive',
    'Address_60': 'Beech Oak Ivy 216 Drive',
    'Address_61': 'Elm Cherry Ash Linden 796 Avenue',
    'Address_62': 'Hazel Ash Ivy 1039 Avenue',
    'Address_63': 'Cherry Beech 604 Road',
    'Address_64': 'Ivy Hazel Beech Oak 452 Drive',
    'Address_65': 'Ivy Ash Willow 865 Avenue',
    'Address_66': 'Holly Hazel Oak 891 Avenue',
    'Address_67': 'Cedar Beech 1067 Drive',
    'Address_68': 'Ivy Hazel Elm Birch 292 Street',
    'Address_69': 'Hazel Maple Cedar Ash 924 Avenue',
    'Address_70': 'Ash Willow Cedar Linden 627 Avenue',
    'Address_71': 'Elm Hazel Cedar Ash 252 Drive',
    'Address_72': 'Maple Ash 61 Street',
    'Address_73': 'Birch Holly Maple Willow 886 Road',
    'Address_74': 'Pine Birch 264 Avenue',
    'Address_75': 'Pine Ivy Willow 1178 Drive',
    'Address_76': 'Birch Cherry Pine 17 Street',
    'Address_77': 'Elm Linden Birch Beech 189 Avenue',
    'Address_78': 'Maple Ivy 191 Road',
    'Address_79': 'Hazel Ash Cherry 447 Road',
    'Address_80': 'Cherry Birch 661 Road',
    'Address_81': 'Beech Oak Cherry Willow 69 Avenue',
    'Address_82': 'Beech Hazel Cherry 1005 Drive',
    'Address_83': 'Oak Linden Ivy 1194 Road',
    'Address_84': 'Willow Elm Hazel Ash 1014 Drive',
    'Address_85': 'Hazel Ash Holly Elm 1184 Drive',
    'Address_86': 'Ash Pine 758 Avenue',
    'Address_87': 'Pine Willow 270 Avenue',
    'Address_88': 'Linden Holly 875 Road',
    'Address_89': 'Hazel Ivy Birch 841 Avenue',
    'Address_90': 'Ivy Willow Elm 619 Street',
    'Address_91': 'Cherry Birch Maple Ivy 573 Avenue',
    'Address_92': 'Birch Elm 843 Street',
    'Address_93': 'Maple Cherry 282 Avenue',
    'Address_94': 'Elm Birch 1118 Avenue',
    'Address_95': 'Maple Beech Cedar 1061 Avenue',
    'Address_96': 'Cedar Willow Ivy 1193 Drive',
    'Address_97': 'Pine Elm 135 Drive',
    'Address_98': 'Cedar Willow 211 Drive',
    'Address_99': 'Hazel Elm Cherry 448 Drive',
    'Address_100': 'Cedar Holly Maple 521 Avenue',
}